const ActionTypes = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOAD_DATA: 'LOAD_DATA',
  LOAD_DATA_FAIL: 'LOAD_DATA_FAIL',
  LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
  LOGOUT: 'LOGOUT',
  LOGOUT_FAIL: 'LOGOUT_FAIL',
  REGISTER: 'REGISTER',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL'
}

export default ActionTypes;